import {
  Activity,
  ArrowLeftRight,
  BarChart3,
  Beaker,
  BookOpen,
  CalendarCheck,
  Calculator,
  Camera,
  Factory,
  FileCheck,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Landmark,
  Receipt,
  RefreshCcw,
  Scale,
  ShieldCheck,
  Sparkles,
  Truck,
  Users,
  Wallet,
  Zap,
} from 'lucide-react';
import type { NavGroup } from './sidebarNav.types';

export const fiscalNavGroup: NavGroup = {
  id: 'fiscal',
  label: 'Fiscal & Documentos',
  icon: FileText,
  items: [
    {
      label: 'Quantum-Sentinel: Tributário',
      icon: Scale,
      href: '/tributario/dashboard',
      highlight: true,
      badgeKey: 'tributario',
      sectionHeader: 'Tributário',
    },
    { label: 'Reforma Tributária', icon: Scale, href: '/reforma-tributaria/visao-geral' },
    { label: 'Split Payment', icon: ArrowLeftRight, href: '/tributario/split-payment' },
    { label: 'Conciliação Tributária', icon: RefreshCcw, href: '/tributario/conciliacao' },
    { label: 'Incentivos Fiscais', icon: Zap, href: '/tributario/incentivos' },
    { label: 'Compliance & Auditoria', icon: ShieldCheck, href: '/tributario/auditoria' },
    { label: 'Comparativo Regimes', icon: Scale, href: '/tributario/comparativo' },
    { label: 'Cashback Simulador', icon: Wallet, href: '/tributario/cashback' },
    {
      label: 'Importação XML',
      icon: FileSpreadsheet,
      href: '/tributario/importacao-xml',
      sectionHeader: 'Documentos Fiscais',
    },
    { label: 'Exportação SPED', icon: BookOpen, href: '/tributario/sped' },
    {
      label: 'Relatórios Contábeis',
      icon: FileSpreadsheet,
      href: '/tributario/relatorios-contabeis',
    },
    { label: 'PER/DCOMP', icon: FileText, href: '/tributario/per-dcomp' },
    { label: 'Retenções na Fonte', icon: Receipt, href: '/tributario/retencoes' },
    { label: 'Monofásico PIS/COFINS', icon: Beaker, href: '/tributario/monofasico' },
    { label: 'Encargos de Folha (RAT/FAP)', icon: Users, href: '/tributario/folha-encargos' },
    { label: 'ICMS-ST e DIFAL', icon: Truck, href: '/tributario/icms-st' },
    { label: 'IPI e ISS', icon: Factory, href: '/tributario/ipi-iss' },
    { label: 'PIS/COFINS (créditos)', icon: Receipt, href: '/tributario/pis-cofins' },
    {
      label: 'IRPJ/CSLL (Lucro Real)',
      icon: Landmark,
      href: '/tributario/irpj-csll',
      sectionHeader: 'Contabilidade & Compliance',
    },
    { label: 'DARF Consolidado', icon: Receipt, href: '/tributario/darf' },
    { label: 'Obrigações Acessórias', icon: CalendarCheck, href: '/tributario/obrigacoes' },
    {
      label: 'Comparativo de Conformidade',
      icon: BarChart3,
      href: '/tributario/comparativo-conformidade',
    },
    { label: 'Preferências do Resumo', icon: BarChart3, href: '/tributario/preferencias-digest' },
    {
      label: 'Observabilidade do Resumo',
      icon: BarChart3,
      href: '/tributario/observabilidade-digest',
    },
    {
      label: 'Fechamento Mensal',
      icon: FileCheck,
      href: '/tributario/fechamento-mensal',
      highlight: true,
    },
    {
      label: 'Relatórios & BI',
      icon: FileText,
      href: '/relatorios',
      highlight: true,
      sectionHeader: 'Relatórios & Ferramentas',
    },
    {
      label: 'Simulação de Regimes',
      icon: Calculator,
      href: '/tributario/simulacao-regimes',
      highlight: true,
    },
    {
      label: 'Oportunidades de Elisão',
      icon: Sparkles,
      href: '/tributario/oportunidades-elisao',
      highlight: true,
    },
    {
      label: 'Projeção 2026-2033',
      icon: BarChart3,
      href: '/tributario/projecao-reforma',
      highlight: true,
    },
    {
      label: 'Histórico Tributário',
      icon: FileSpreadsheet,
      href: '/tributario/historico-financeiro',
    },
    {
      label: 'Certificados Digitais A1',
      icon: ShieldCheck,
      href: '/tributario/certificados-digitais',
      highlight: true,
    },
    {
      label: 'NF-e Recebidas (SEFAZ)',
      icon: FileText,
      href: '/tributario/nfe-recebidas',
      highlight: true,
    },
    { label: 'Observabilidade SEFAZ', icon: Activity, href: '/tributario/sefaz-observabilidade' },
    { label: 'Notas Fiscais', icon: FileText, href: '/notas-fiscais' },
    { label: 'Demonstrativos', icon: FileSpreadsheet, href: '/demonstrativos' },
    { label: 'Contabilidade & SPED', icon: BookOpen, href: '/contabilidade' },
    { label: 'Contratos', icon: FileCheck, href: '/contratos' },
    { label: 'Assinatura Digital', icon: FileSignature, href: '/assinatura-digital' },
    { label: 'Comprovante OCR', icon: Camera, href: '/comprovante-ocr' },
    {
      label: 'Cofre de Integridade',
      icon: ShieldCheck,
      href: '/contas-pagar/bloqueios',
      highlight: true,
    },
  ],
};
