import type { Obrigacao } from './types';

/**
 * Catálogo de obrigações acessórias federais e estaduais recorrentes.
 * Prazos conforme legislação vigente em 2024/2025.
 */
export const OBRIGACOES: readonly Obrigacao[] = [
  {
    id: 'efd_contribuicoes',
    nome: 'EFD-Contribuições',
    descricao: 'Escrituração digital de PIS/Pasep, COFINS e Contribuição Previdenciária sobre Receita Bruta.',
    orgao: 'RFB',
    periodicidade: 'mensal',
    regra: { tipo: 'enesimo_dia_util', n: 10, mesesApos: 2 },
    ajuste: 'posterga',
    regimes: ['presumido', 'real'],
    baseLegal: 'IN RFB 1.252/2012, art. 7º',
    baseMulta: 'faturamento',
    multaMensal: 0.005,
    multaTeto: 0.2,
    multaMinima: 500,
  },
  {
    id: 'efd_icms_ipi',
    nome: 'EFD ICMS/IPI',
    descricao: 'Escrituração fiscal digital de ICMS e IPI (prazo estadual, padrão dia 20).',
    orgao: 'SEFAZ',
    periodicidade: 'mensal',
    regra: { tipo: 'dia_fixo', dia: 20, mesesApos: 1 },
    ajuste: 'posterga',
    regimes: ['presumido', 'real'],
    baseLegal: 'Convênio ICMS 143/2006 e legislação da UF',
    baseMulta: 'fixa',
    multaMensal: 0,
    multaTeto: 0,
    multaMinima: 500,
  },
  {
    id: 'dctfweb',
    nome: 'DCTFWeb',
    descricao: 'Confissão de dívida das contribuições previdenciárias e de terceiros.',
    orgao: 'RFB',
    periodicidade: 'mensal',
    regra: { tipo: 'dia_fixo', dia: 15, mesesApos: 1 },
    ajuste: 'antecipa',
    regimes: ['todos'],
    baseLegal: 'IN RFB 2.005/2021, art. 19',
    baseMulta: 'tributos_declarados',
    multaMensal: 0.02,
    multaTeto: 0.2,
    multaMinima: 200,
  },
  {
    id: 'efd_reinf',
    nome: 'EFD-Reinf',
    descricao: 'Retenções e informações da contribuição previdenciária substituída.',
    orgao: 'RFB',
    periodicidade: 'mensal',
    regra: { tipo: 'dia_fixo', dia: 15, mesesApos: 1 },
    ajuste: 'antecipa',
    regimes: ['todos'],
    baseLegal: 'IN RFB 2.043/2021, art. 3º',
    baseMulta: 'tributos_declarados',
    multaMensal: 0.02,
    multaTeto: 0.2,
    multaMinima: 500,
  },
  {
    id: 'esocial',
    nome: 'eSocial — folha mensal',
    descricao: 'Envio dos eventos periódicos de folha de pagamento (S-1200/S-1210/S-1299).',
    orgao: 'RFB',
    periodicidade: 'mensal',
    regra: { tipo: 'dia_fixo', dia: 15, mesesApos: 1 },
    ajuste: 'antecipa',
    regimes: ['todos'],
    baseLegal: 'Decreto 8.373/2014 e Manual do eSocial S-1.2',
    baseMulta: 'tributos_declarados',
    multaMensal: 0.02,
    multaTeto: 0.2,
    multaMinima: 200,
  },
  {
    id: 'darf_das',
    nome: 'PGDAS-D (Simples Nacional)',
    descricao: 'Declaração e apuração mensal do Simples Nacional.',
    orgao: 'RFB',
    periodicidade: 'mensal',
    regra: { tipo: 'dia_fixo', dia: 20, mesesApos: 1 },
    ajuste: 'antecipa',
    regimes: ['simples'],
    baseLegal: 'LC 123/2006, art. 21, §1º',
    baseMulta: 'tributos_declarados',
    multaMensal: 0.02,
    multaTeto: 0.2,
    multaMinima: 50,
  },
  {
    id: 'dirbi',
    nome: 'DIRBI',
    descricao: 'Declaração de Incentivos, Renúncias, Benefícios e Imunidades de Natureza Tributária.',
    orgao: 'RFB',
    periodicidade: 'mensal',
    regra: { tipo: 'dia_fixo', dia: 20, mesesApos: 2 },
    ajuste: 'antecipa',
    regimes: ['presumido', 'real'],
    baseLegal: 'IN RFB 2.198/2024, art. 3º',
    baseMulta: 'faturamento',
    multaMensal: 0.005,
    multaTeto: 0.3,
    multaMinima: 0,
  },
  {
    id: 'ecd',
    nome: 'ECD — Escrituração Contábil Digital',
    descricao: 'Livros Diário e Razão digitais do exercício encerrado.',
    orgao: 'RFB',
    periodicidade: 'anual',
    regra: { tipo: 'dia_fixo_anual', mes: 5, ultimoDiaUtil: true },
    ajuste: 'antecipa',
    regimes: ['presumido', 'real'],
    baseLegal: 'IN RFB 2.003/2021, art. 5º',
    baseMulta: 'faturamento',
    multaMensal: 0.0025,
    multaTeto: 0.1,
    multaMinima: 500,
  },
  {
    id: 'ecf',
    nome: 'ECF — Escrituração Contábil Fiscal',
    descricao: 'Apuração do IRPJ e da CSLL do exercício, com LALUR/LACS digitais.',
    orgao: 'RFB',
    periodicidade: 'anual',
    regra: { tipo: 'dia_fixo_anual', mes: 7, ultimoDiaUtil: true },
    ajuste: 'antecipa',
    regimes: ['presumido', 'real'],
    baseLegal: 'IN RFB 2.004/2021, art. 3º',
    baseMulta: 'tributos_declarados',
    multaMensal: 0.005,
    multaTeto: 0.1,
    multaMinima: 500,
  },
  {
    id: 'defis',
    nome: 'DEFIS',
    descricao: 'Declaração de Informações Socioeconômicas e Fiscais do Simples Nacional.',
    orgao: 'RFB',
    periodicidade: 'anual',
    regra: { tipo: 'dia_fixo_anual', mes: 3, ultimoDiaUtil: true },
    ajuste: 'antecipa',
    regimes: ['simples'],
    baseLegal: 'Resolução CGSN 140/2018, art. 72',
    baseMulta: 'fixa',
    multaMensal: 0,
    multaTeto: 0,
    multaMinima: 200,
  },
] as const;

/** Busca uma obrigação pelo identificador. */
export function buscarObrigacao(id: string): Obrigacao | undefined {
  return OBRIGACOES.find((o) => o.id === id);
}
