export * from './types';
export * from './orquestrador-elisao';
export { detectarJCP } from './detectar-jcp';
export { detectarReintegra } from './detectar-reintegra';
export { detectarMsLc224 } from './detectar-ms-lc224';
export { detectarHolding } from './detectar-holding';
export { detectarPAT } from './detectar-pat';
export { detectarLeiBem } from './detectar-lei-bem';
export { detectarDrawback } from './detectar-drawback';
export { detectarSubvencaoIcms } from './detectar-subvencao-icms';
export { detectarBonificacao } from './detectar-bonificacao';
export { detectarDeliberacaoLucros } from './detectar-deliberacao-lucros';
export { detectarRecuperacaoPisCofins } from './detectar-recuperacao-pis-cofins';
export { detectarDepreciacaoAcelerada } from './detectar-depreciacao-acelerada';
export { detectarSudeneSudam } from './detectar-sudene-sudam';
